name: "Netlify Deploy"

on:
  push:
    branches:
      - main # Ana dalda her push'ta çalışır, isterseniz başka dallar ekleyebilirsiniz

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      # 1. Depoyu checkout et
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # 2. Node.js ortamını kur (pnpm için)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      # 4. pnpm-workspace.yaml dosyasını oluştur
      - name: Create pnpm-workspace.yaml
        run: |
          if [ ! -f pnpm-workspace.yaml ]; then
            cat > pnpm-workspace.yaml << EOL
            packages:
              - core
              - form-builder
            EOL
          fi

      # 5. package.json dosyasını oluştur
      - name: Create package.json
        run: |
          if [ ! -f package.json ]; then
            cat > package.json << EOL
            {}
            EOL
          fi

      # 6. pnpm install çalıştır
      - name: Install dependencies
        run: pnpm install

      # 7. Storybook'u build et
      - name: Build Storybook
        run: cd form-builder && pnpm build-storybook

      # 8. Netlify'ye deploy et
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deploy from push ${GITHUB_SHA}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: form-builder/storybook-static # Statik sitenin klasörü
